### ISSUE TITLE
julia 0.7.0 is using code of `05compat` branch

### ISSUE THREAD

**Issue by tpdsantos** [JuliaIO/SerialPorts.jl#29]
Hi, I use this package for a while, but when I changed to julia 0.7.0, the `write` function stopped working with strings. After fighting with it for a few hours, I saw that the module used by 0.7.0 is the same as the branch `05compat`. It made sense because there were still several deprecation warnings. I solved it by tracking the master manually with `]add SerialPorts#master` but it took me a while to figure that out... Is probably the registered branch mistaken?

Thanks in advance!

**Comment by tpdsantos** [comment]
I see... anyway, the master branch works great so it's fine :)

**Comment by sjkelly** [comment]
That is great to hear. Please let me know if there are any bugs on master that need to be fixed before I submit to METADATA.

**Comment by tpdsantos** [comment]
Sure, I will, but for now it works great no problems at all :)
